name    'mbklein-fcrepo'
version '0.0.1'
source 'http://github.com/mbklein/puppet-fcrepo'
author 'mbklein'
license 'Apache License, Version 2.0'
summary 'Install Fedora Repository under Tomcat'
description 'Install Fedora Repository under Tomcat'
project_page 'http://github.com/mbklein/puppet-fcrepo'
dependency 'nanliu/staging'
